-- Insertion des fonctionnalités
INSERT INTO "APPINFO_SCH"."FUNCTIONALITY" (ID, TYPE, NAME) VALUES (FUNCTIONALITY_SEQ.nextval, 'CONFIGURATION', 'Contacts');
INSERT INTO "APPINFO_SCH"."FUNCTIONALITY" (ID, TYPE, NAME) VALUES (FUNCTIONALITY_SEQ.nextval, 'CONFIGURATION', 'Liste de diffusion');
INSERT INTO "APPINFO_SCH"."FUNCTIONALITY" (ID, TYPE, NAME) VALUES (FUNCTIONALITY_SEQ.nextval, 'CONFIGURATION', 'Catégories');
INSERT INTO "APPINFO_SCH"."FUNCTIONALITY" (ID, TYPE, NAME) VALUES (FUNCTIONALITY_SEQ.nextval, 'CONFIGURATION', 'Alarmes');
INSERT INTO "APPINFO_SCH"."FUNCTIONALITY" (ID, TYPE, NAME) VALUES (FUNCTIONALITY_SEQ.nextval, 'CONFIGURATION', 'Alertes');
INSERT INTO "APPINFO_SCH"."FUNCTIONALITY" (ID, TYPE, NAME) VALUES (FUNCTIONALITY_SEQ.nextval, 'CONFIGURATION', 'Profils');
INSERT INTO "APPINFO_SCH"."FUNCTIONALITY" (ID, TYPE, NAME) VALUES (FUNCTIONALITY_SEQ.nextval, 'CONFIGURATION', 'Fériés');
INSERT INTO "APPINFO_SCH"."FUNCTIONALITY" (ID, TYPE, NAME) VALUES (FUNCTIONALITY_SEQ.nextval, 'MAINTENANCE', 'Maintenance');
INSERT INTO "APPINFO_SCH"."FUNCTIONALITY" (ID, TYPE, NAME) VALUES (FUNCTIONALITY_SEQ.nextval, 'COMMUNICATION', 'Communication');
INSERT INTO "APPINFO_SCH"."FUNCTIONALITY" (ID, TYPE, NAME) VALUES (FUNCTIONALITY_SEQ.nextval, 'HISTORIQUE', 'Historique');
