--Uniformiser le nom de l'alerte en majuscule
UPDATE appinfo_sch.alert SET name = UPPER(name);

--UPDADE ALL DATA
UPDATE "APPINFO_SCH"."MAINTENANCE" SET LAST_MODIFIED_BY = 'SYS' , CREATED_BY = 'SYS' , CREATED_DATE = CURRENT_TIMESTAMP;
UPDATE "APPINFO_SCH"."CONTACT" SET LAST_MODIFIED_BY = 'SYS' , CREATED_BY = 'SYS' , CREATED_DATE = CURRENT_TIMESTAMP;
UPDATE "APPINFO_SCH"."DIFFUSION_GROUP" SET LAST_MODIFIED_BY = 'SYS' , CREATED_BY = 'SYS' , CREATED_DATE = CURRENT_TIMESTAMP;
UPDATE "APPINFO_SCH"."CATEGORY" SET LAST_MODIFIED_BY = 'SYS' , CREATED_BY = 'SYS' , CREATED_DATE = CURRENT_TIMESTAMP;
UPDATE "APPINFO_SCH"."HOLIDAY" SET LAST_MODIFIED_BY = 'SYS' , CREATED_BY = 'SYS' , CREATED_DATE = CURRENT_TIMESTAMP;
UPDATE "APPINFO_SCH"."ALARM" SET LAST_MODIFIED_BY = 'SYS' , CREATED_BY = 'SYS' , CREATED_DATE = CURRENT_TIMESTAMP;
UPDATE "APPINFO_SCH"."ALERT" SET LAST_MODIFIED_BY = 'SYS' , CREATED_BY = 'SYS' , CREATED_DATE = CURRENT_TIMESTAMP;
COMMIT;