-- Add column Table MAINTENANCE
ALTER TABLE APPINFO_SCH."MAINTENANCE" ADD "LAST_MODIFIED_DATE" TIMESTAMP;
ALTER TABLE APPINFO_SCH."MAINTENANCE" ADD "LAST_MODIFIED_BY" VARCHAR2(64 CHAR);
ALTER TABLE APPINFO_SCH."MAINTENANCE" ADD "CREATED_BY" VARCHAR2(64 CHAR);
ALTER TABLE APPINFO_SCH."MAINTENANCE" ADD "CREATED_DATE" TIMESTAMP;

--Add column Table CONTACT
ALTER TABLE APPINFO_SCH."CONTACT" ADD "LAST_MODIFIED_DATE" TIMESTAMP;
ALTER TABLE APPINFO_SCH."CONTACT" ADD "LAST_MODIFIED_BY" VARCHAR2(64 CHAR);
ALTER TABLE APPINFO_SCH."CONTACT" ADD "CREATED_BY" VARCHAR2(64 CHAR);
ALTER TABLE APPINFO_SCH."CONTACT" ADD "CREATED_DATE" TIMESTAMP;

--Add column Table DIFFUSION_GROUP
ALTER TABLE APPINFO_SCH."DIFFUSION_GROUP" ADD "LAST_MODIFIED_DATE" TIMESTAMP;
ALTER TABLE APPINFO_SCH."DIFFUSION_GROUP" ADD "LAST_MODIFIED_BY" VARCHAR2(64 CHAR);
ALTER TABLE APPINFO_SCH."DIFFUSION_GROUP" ADD "CREATED_BY" VARCHAR2(64 CHAR);
ALTER TABLE APPINFO_SCH."DIFFUSION_GROUP" ADD "CREATED_DATE" TIMESTAMP;

--Add column Table CATEGORY
ALTER TABLE APPINFO_SCH."CATEGORY" ADD "LAST_MODIFIED_DATE" TIMESTAMP;
ALTER TABLE APPINFO_SCH."CATEGORY" ADD "LAST_MODIFIED_BY" VARCHAR2(64 CHAR);
ALTER TABLE APPINFO_SCH."CATEGORY" ADD "CREATED_BY" VARCHAR2(64 CHAR);
ALTER TABLE APPINFO_SCH."CATEGORY" ADD "CREATED_DATE" TIMESTAMP;

--Add column Table HOLIDAY
ALTER TABLE APPINFO_SCH."HOLIDAY" ADD "LAST_MODIFIED_DATE" TIMESTAMP;
ALTER TABLE APPINFO_SCH."HOLIDAY" ADD "LAST_MODIFIED_BY" VARCHAR2(64 CHAR);
ALTER TABLE APPINFO_SCH."HOLIDAY" ADD "CREATED_BY" VARCHAR2(64 CHAR);
ALTER TABLE APPINFO_SCH."HOLIDAY" ADD "CREATED_DATE" TIMESTAMP;

--Add column Table ALARM
ALTER TABLE APPINFO_SCH."ALARM" ADD "LAST_MODIFIED_DATE" TIMESTAMP;
ALTER TABLE APPINFO_SCH."ALARM" ADD "LAST_MODIFIED_BY" VARCHAR2(64 CHAR);
ALTER TABLE APPINFO_SCH."ALARM" ADD "CREATED_BY" VARCHAR2(64 CHAR);
ALTER TABLE APPINFO_SCH."ALARM" ADD "CREATED_DATE" TIMESTAMP;

--Add column Table ALERT
ALTER TABLE APPINFO_SCH."ALERT" ADD "LAST_MODIFIED_DATE" TIMESTAMP;
ALTER TABLE APPINFO_SCH."ALERT" ADD "LAST_MODIFIED_BY" VARCHAR2(64 CHAR);
ALTER TABLE APPINFO_SCH."ALERT" ADD "CREATED_BY" VARCHAR2(64 CHAR);
ALTER TABLE APPINFO_SCH."ALERT" ADD "CREATED_DATE" TIMESTAMP;