ALTER TABLE  APPINFO_SCH.METEO MODIFY AGENDA_PERIMETRE varchar2(200 char);
ALTER TABLE  APPINFO_SCH.METEO MODIFY AGENDA_NATURE_INTERVENTION varchar2(200 char);
ALTER TABLE  APPINFO_SCH.METEO MODIFY AGENDA_IMPACT varchar2(150 char);
COMMIT;